### ISSUE TITLE
npm install error, missing dependencies.

### ISSUE THREAD

**Issue by ARXChrono** [digisavvy/some-like-it-neat#111]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
npm WARN gulp-jshint@2.0.4 requires a peer of jshint@2.x but none was installed.

I:\xxxx\xampp\htdocs\wp-content\themes\xxxx>gulp
module.js:471
    throw err;
    ^

Error: Cannot find module 'jshint/src/cli'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (I:\xxxx\xampp\htdocs\wp-content\themes\xxxx\node_modules\gulp-jshint\src\extract.js:1:79)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by digisavvy** [comment]
Hey there,
I'm still looking into this issue.
What I have found to work around it is to do the following:
- run `npm gulp-jshint' and that seems to help resolve that issue.

**Comment by digisavvy** [comment]
Alrighty, this has been addressed here: 09989b2fa3fc866ea1db83388f57a1d0c8aa5f04
