### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by socheon** [digisavvy/some-like-it-neat#94]
Anyone got this error when running `gulp`?

```
[09:58:16] Starting 'styles'...
[09:58:16] Starting 'js'...
[09:58:16] Starting 'jsHint'...
[09:58:16] Starting 'images'...
Anyway got this error when running gulp?

[09:58:16] Starting 'browser-sync'...
[09:58:16] Finished 'browser-sync' after 88 ms
[09:58:16] Starting 'phpcs'...
[09:58:16] gulp-imagemin: Minified 0 images
[09:58:16] Finished 'images' after 140 ms
[09:58:16] Finished 'jsHint' after 177 ms
[09:58:16] Finished 'js' after 185 ms
events.js:142
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at WriteWrap.afterWrite (net.js:764:14)
```

**Comment by socheon** [comment]
I figured out. I ignored this step `php composer.phar install`
